#!/bin/bash
#
# jedartois@gmail.com
# erwan.daubert@gmail.com
#
# script install and configure lxc for ubuntu
# Tested with Ubuntu Server 13.10 kernel 3.11.0-15-generic


alreadyAPTDone=`cat /etc/apt/sources.list | grep "http://ppa.launchpad.net/webupd8team/java/ubuntu"`

if [ "$alreadyAPTDone" == "" ]; then
	echo "Updating /etc/apt/sources.list"
	cp /etc/apt/sources.list /etc/apt/sources.list.back
	echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu raring main" | tee -a /etc/apt/sources.list
	echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu raring main" | tee -a /etc/apt/sources.list
	# Update local software list
	sudo apt-get update
fi
 
echo "Accept Oracle software license (only required once)"
echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
 
echo "Install Oracle JDK7"
sudo apt-get install oracle-java7-installer --force-yes -y

kevoreeVersion="RELEASE"
kevoreeLibraryVersion="RELEASE"
watchdogVersion="0.20"

echo "Can you please tell me the version of kevoree ?"
read kevoreeVersion

echo "Can you please tell me the version of kevoree-library ?"
read kevoreeLibraryVersion

echo "Can you please tell me the version of the kevoree-watchdog(eg. 0.20) ?"
read watchdogVersion

echo "Configure Kevoree Watchdog"
apt-get install wget
wget "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.kevoree.watchdog&a=org.kevoree.watchdog&v=$watchdogVersion&p=deb" --content-disposition -O /tmp/kevoree.watchdog.deb
if [ $? -ne 0 ]; then
	wget "http://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=org.kevoree.watchdog&a=org.kevoree.watchdog&v=$watchdogVersion&p=deb" --content-disposition -O /tmp/kevoree.watchdog.deb
fi
dpkg -i /tmp/kevoree.watchdog.deb
rm /tmp/kevoree.watchdog.deb

echo "Configure kevoree watchdog"
cat > "/etc/kevoree/config" << EOF
KEVOREE_USER=root
KEVOREE_GROUP=kevoree
KEVOREE_VERSION=$kevoreeVersion
NODE_NAME=$(hostname)
PING_PORT=9999
PING_TIMEOUT=3000
BOOTMODEL=/etc/kevoree/boot.kevs
EOF

#create model
echo "Configure kevoree bootstrapmodel"
touch /etc/kevoree/boot.kevs
cat > "/etc/kevoree/boot.kevs" << EOF
repo "https://repo1.maven.org/maven2"
repo "https://oss.sonatype.org/content/groups/public/"

include mvn:org.kevoree.library.java:org.kevoree.library.java.ws:$kevoreeLibraryVersion
include mvn:org.kevoree.library.cloud:org.kevoree.library.cloud.lxc:$kevoreeLibraryVersion

add $(hostname) : LXCNode

add sync : WSGroup
set sync.port/$(hostname) = "9000"
attach $(hostname) sync

include mvn:org.kevoree.library.cloud:org.kevoree.library.cloud.web:$kevoreeLibraryVersion

add $(hostname).web : WebFrontend
EOF
