#!/bin/bash
#
# erwan.daubert@gmail.com
#
# script install and configure lxc for ubuntu
# Tested with Ubuntu Server 13.10 kernel 3.11.0-15-generic

wget "http://repository.sonatype.org/service/local/artifact/maven/redirect?r=central-proxy&g=org.kevoree.watchdog&a=org.kevoree.watchdog&v=RELEASE&p=deb"  --content-disposition --no-check-certificate
sudo dpkg -i org.kevoree.watchdog*.deb
rm org.kevoree.watchdog*.deb