#!/bin/bash
#
# jedartois@gmail.com
# erwan.daubert@gmail.com
#
# script install and configure lxc for ubuntu
# Tested with Ubuntu Server 13.10 kernel 3.11.0-15-generic

kevoreeVersion="RELEASE"
kevoreeLibraryVersion="RELEASE"

echo "Can you please tell me the version of kevoree ?"
read kevoreeVersion

echo "Can you please tell me the version of kevoree-library ?"
read kevoreeLibraryVersion

echo "Configure kevoree watchdog"
cat > "/etc/kevoree/config" << EOF
KEVOREE_USER=root
KEVOREE_GROUP=kevoree
KEVOREE_VERSION=$kevoreeVersion
NODE_NAME=$(hostname)
PING_PORT=9999
PING_TIMEOUT=3000
BOOTMODEL=/etc/kevoree/boot.kevs
EOF

#create model
echo "Configure kevoree bootstrapmodel"
touch /etc/kevoree/boot.kevs
cat > "/etc/kevoree/boot.kevs" << EOF
repo "https://repo1.maven.org/maven2"
repo "https://oss.sonatype.org/content/groups/public/"

include mvn:org.kevoree.library.java:org.kevoree.library.java.ws:$kevoreeLibraryVersion
include mvn:org.kevoree.library.cloud:org.kevoree.library.cloud.lxc:$kevoreeLibraryVersion

add $(hostname) : LXCNode

add sync : WSGroup
set sync.port/$(hostname) = "9000"
attach $(hostname) sync

include mvn:org.kevoree.library.cloud:org.kevoree.library.cloud.web:$kevoreeLibraryVersion

add $(hostname).web : WebFrontend
EOF
