---
language: java

# get us on the new container based builds, we're not using any fancyness
sudo: false

before_install:
  - export MAVEN_OPTS="-Xms2048m -Xmx2048m -XX:PermSize=512m"

cache:
  directories:
    - $HOME/.m2

script: mvn -B install

jdk:
  - oraclejdk8

branches:
  only:
    - master
