#!/bin/bash

# jedartois@gmail.com

# What lxc container to clone
LXC_BASE=""
# $2 is a path to bind mount e.g. /tmp/foo.
LXC_BIND=""

usage() {
    echo "usage: lxc-backup -n name"
}

help() {
    usage
    echo
    echo "Backup of a container"
    echo
    echo "Options:"
    echo "name        : name of the container"
    echo
    echo "if a COMMAND is given, then the container will run only as long"
    echo "as the command runs.  If no COMMAND is given, this command will"
    echo "wait until the container is shut down"
}

shortoptions='h:n:'
longoptions='help,name:'

LXC_RUNNING=0

getopt=$(getopt -o $shortoptions --longoptions  $longoptions -- "$@")
if [ $? != 0 ]; then
    usage
    exit 1;
fi

eval set -- "$getopt"

while true; do
    case "$1" in
        -h|--help)
            help
            exit 1
            ;;
        -n|--name)
            shift
            LXC_NAME=$1
            shift
            ;;
        --)
            shift
            break;;
        *)
            echo $1
            usage
            exit 1
            ;;
    esac
done


COMMAND=$@
COMMAND_LENGTH=$#
LXC_USER=${LXC_USER:-`id -un`}


# validation

if [ -z $LXC_NAME ]; then
    echo "container must be specified"
    usage
    exit 1
fi
if [ ! -d /var/lib/lxc/$LXC_NAME ] ; then
    echo "no such lxc container $LXC_NAME"
    exit 1
fi

if [ ! -d /usr/share/kevoree ] ; then
    echo "kevoree watchdog is not configured"
    exit 1
fi


do_backup()
{
    if [ -d /usr/share/kevoree/lxc/backup/$LXC_NAME ] ; then
       NOW=$(date +"%Y-%m-%d-%H-%M-%S")
       echo "Backup with same lxc container name"
       mkdir /usr/share/kevoree/lxc/backup/$LXC_NAME-$NOW
       mv /usr/share/kevoree/lxc/backup/$LXC_NAME  /usr/share/kevoree/lxc/backup/$LXC_NAME-$NOW
    fi

    mkdir -p /usr/share/kevoree/lxc/backup/$LXC_NAME
    mv /var/lib/lxc/$LXC_NAME /usr/share/kevoree/lxc/backup
}


do_backup